services:
    sql.data:
        container_name: db_service
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${DB_PASSWORD}

    application:
        build: .
        restart: always
        ports: [
            '8080:8080',
            '8081:8081'
        ]
        environment:
            ASPNETCORE_ACCOUNTMANAGEMENT_WEB_CONNECTIONSTRING: Server=sql.data;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
        depends_on:
            - sql.data